name: stockrates
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  http: ^0.12.1
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7
  modal_progress_hud: ^0.1.3
  google_sign_in: ^4.5.1
  intl: ^0.16.1
  flutter_webview_plugin: ^0.3.11
  provider: ^4.3.3



dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: "latest version"



flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"


flutter:

  uses-material-design: true

  assets:
    - assets/

